# This GitHub action re-creates the documentation for the current project version
# whenever a pull-request gets opened, updated or closed.
name: deploy-pages
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    types:
      - opened
      - synchronize
      - closed
permissions:
  contents: write
  pages: write
jobs:

  deploy-pages:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-repository
      - name: 'Deploy to pages with mike'
        run: |
          git fetch origin gh-pages --depth=1
          export CI_DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
          export CLEANED_REF_NAME=$(echo $GITHUB_REF_NAME | tr / _)
          echo $CI_DEFAULT_BRANCH
          echo $CLEANED_REF_NAME
          poetry run mike deploy $CLEANED_REF_NAME -u -p
          if poetry run mike list "" | grep -Fqx $CI_DEFAULT_BRANCH; then
            poetry run mike set-default $CI_DEFAULT_BRANCH -p
          else
            echo "Documentation version $CI_DEFAULT_BRANCH does not exist yet. Set default to currently build version $CLEANED_REF_NAME"
            poetry run mike set-default $CLEANED_REF_NAME -p
          fi
