# This GitHub action creates the initial documentation on a push event to the 'main' branch
# with commit message 'Instantiated Explora Template'
name: initial-commit
on: 
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
jobs:

  pages:
    # TODO: Use docker image created with .devcontainer
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Instantiated Explora Template')
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-repository
      - name: 'Deploy to pages with mike'
        run: |
          poetry run mike deploy v$(poetry version --short) latest -u -p
          poetry run mike set-default latest -p
  